In [ ]:
# Import the needed libraries

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [6]:
import numpy as np
A=np.random.rand(10,10)
B= np.amax(A)
C= np.amin(A)
print("minimum value :",B)
print("maximum value :", C)

minimum value : 0.992251083229465
maximum value : 0.003133286507104427


**15. Create a 2d array with 1 on the border and 0 inside**

In [8]:
import numpy as np
A= np.ones((7,7))
A[1:-1,1:-1]=0
print(A)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
